[package]
name = "sm-pkg"
version = "0.1.0"
description = "A sourcemod package manager"
readme = "README.md"
license = "MIT"
edition = "2024"
authors = [
    "Leigh MacDonald <leigh.macdonald@gmail.com>"
]

[dependencies]
archive = "0.3.0"
async-std = "1.13.2"
clap = { version = "4.5.54", features = ["derive"] }
flate2 = { version = "1.1.8", features = ["zlib-rs"] }
git2 = { version = "0.20.3", features = ["https", "ssh"] }
inquire = "0.9.2"
lazy_static = "1.5.0"
minijinja = "2.14.0"
minijinja-embed = "2.14.0"
reqwest = "0.13.1"
resolve-path = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tar = "0.4.44"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
update = "0.0.0"

[build-dependencies]
minijinja-embed = "2.14.0"
